db:
  image: casa.docker/mysql:5.7
  hostname: db
  stdin_open: true
  tty: true
  restart: always
  ports:
  - "3306:3306"
  environment:
  - MYSQL_ROOT_PASSWORD=mysql
  - MYSQL_USER=planets
  - MYSQL_PASSWORD=1planets!
  - MYSQL_DATABASE=planetsdb

web:
  image: casa.docker/wildfly-mysql:9.0.2
  hostname: web
  # http://docs.docker.com/compose/networking/
  command: -Dmysql.ipaddress=continuousdelivery_db_1 -Dmysql.port=3306 -Dmysql.database=planetsdb -Dmysql.username=planets -Dmysql.password=1planets!
  stdin_open: true
  tty: true
  restart: always
  ports:
  - "8080:8080"
  - "9990:9990"
