db:
  image: casa.docker/mysql-no-volumes:5.7
  hostname: planets-db
  container_name: mysql-planets-db
  stdin_open: true
  tty: true
  ports:
  - "3306:3306"
  environment:
  - MYSQL_ROOT_PASSWORD=mysql
  - MYSQL_USER=planets
  - MYSQL_PASSWORD=1planets!
  - MYSQL_DATABASE=planetsdb

web:
  image: casa.docker/wildfly-mysql:9.0.2
  hostname: web
  container_name: planets-web
  # http://docs.docker.com/compose/networking/
  command: -Dmysql.ipaddress=mysql-planets-db -Dmysql.port=3306 -Dmysql.database=planetsdb -Dmysql.username=planets -Dmysql.password=1planets!
  stdin_open: true
  tty: true
  ports:
  - "8080:8080"
  - "9990:9990"
