version: '2'
services:
  sonar-db:
    image: postgres:9.5
    container_name: sonar-db
    environment:
      - POSTGRES_DB=sonar
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar

  nexus:
    image: sonatype/nexus:2.12.0-01
    container_name: nexus
    ports:
      - "172.17.0.1:8081:8081"
    volumes:
      - /opt/docker_volumes/nexus-data:/sonatype-work

  jenkins:
    image: casadocker/jenkins:1.642.2
    container_name: jenkins
    ports:
      - "8088:8080"
    extra_hosts:
      - "docker.host:${DOCKER_IP}"

  sonar:
    image: sonarqube:5.4
    container_name: sonar
    ports:
      - "172.17.0.1:19000:9000"
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonar-db:5432/sonar
